<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?= BASE_URL ?>">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css?v=<?php echo time(); ?>">
    <title>Cartelera</title>
</head>
<body>
<div class="movies-grid">
    <div class="movie-card">

        <?php if (!empty($movie->imagen_base64)): ?>
        <img src="data:<?= $movie->mime ?>;base64,<?= $movie->imagen_base64 ?>"
        alt="<?= htmlspecialchars($movie->titulo) ?>">

        <?php else: ?>
            <div class="placeholder-img">Sin imagen</div>
        <?php endif; ?>

                <div class="movie-info">
                    <h3><?= htmlspecialchars($movie->titulo) ?></h3>
                    <p><?= htmlspecialchars($movie->sinopsis) ?></p>
                    <p><strong>Duración:</strong> <?= $movie->duracion ?> min</p>
                    <p><strong>Puntaje:</strong> <?= $movie->puntaje_promedio ?></p>
                    <a type="button" class="btn btn-view btn-small" href="<?= BASE_URL ?>home">Home</a>
                </div>
    </div>
</div>