<?php require_once 'templates/header.phtml'; ?>

<?php if ($error): ?>
    <div class="alert alert-danger" role="alert">
        <?php echo $error ?>
    </div>
<?php endif ?>
<form method="post" action="login">
    <div class="form-group">
        <label for="email">Email</label>
        <input type=""  class="form-control" id="email" name="email" required>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password"  class="form-control" id="password" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Log In</button>
</form>


<?php require_once 'templates/footer.phtml'; ?>