<?php require_once 'templates/header.phtml'; ?>

<form action="updateMovie/<?= $movie->id ?>" method="POST">
    <h1 class="form-h1">Editar Película</h1>

    <label>Editar titulo:</label>
    <input type="text"  name="titulo" value="<?= htmlspecialchars($movie->titulo) ?>" required>

    <label>Editar duracion:</label>
    <textarea name="duracion" class="form-control" rows="2"></textarea>


    <label >Editar sinopsis:</label>
    <textarea name="sinopsis" class="form-control" rows="2"></textarea>

    <label>Editar puntaje:</label>
    <textarea name="puntaje" class="form-control" rows="2"></textarea>
    
    <label >Editar genero:</label>
        <select required name="genero" class="form-control">
                <option value="1">Accion</option>
                <option value="2">Comedia</option>
                <option value="3">Drama</option>
                <option value="4">Ciencia Ficcion</option>
                <option value="5">Terror</option>
        </select>

    <input type="file" name="img" accept="image/*">
    <button type="submit">Actualizar película</button>
    <a href="updateMovie/<?= $movie->id?>" class="btn btn-primary">Submit</a>
</form>
<?php require_once 'templates/footer.phtml'; ?>